The capstone project

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, r2_score, classification_report
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

In [2]:
df = pd.read_csv('Data-Collisions.csv')
pd.set_option('display.max_columns',None)
df.head()

D:\Users\ShalomCheng\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY REPORTNO  \
0             2 -122.323148  47.703140         1    1307       1307  3502005   
1             1 -122.347294  47.647172         2   52200      52200  2607959   
2             1 -122.334540  47.607871         3   26700      26700  1482393   
3             1 -122.334803  47.604803         4    1144       1144  3503937   
4             2 -122.306426  47.545739         5   17700      17700  1807429   

    STATUS      ADDRTYPE   INTKEY  \
0  Matched  Intersection  37475.0   
1  Matched         Block      NaN   
2  Matched         Block      NaN   
3  Matched         Block      NaN   
4  Matched  Intersection  34387.0   

                                      LOCATION EXCEPTRSNCODE EXCEPTRSNDESC  \
0                   5TH AVE NE AND NE 103RD ST                         NaN   
1   AURORA BR BETWEEN RAYE ST AND BRIDGE WAY N           NaN           NaN   
2  4TH AVE BETWEEN SENECA ST AND UNIVERSITY ST           NaN           NaN   
3     2ND AVE BETWEEN MARION ST AND MADISON ST                         NaN   
4              SWIFT AVE S AND SWIFT AV OFF RP           NaN           NaN   

   SEVERITYCODE.1                    SEVERITYDESC COLLISIONTYPE  PERSONCOUNT  \
0               2                Injury Collision        Angles            2   
1               1  Property Damage Only Collision     Sideswipe            2   
2               1  Property Damage Only Collision    Parked Car            4   
3               1  Property Damage Only Collision         Other            3   
4               2                Injury Collision        Angles            2   

   PEDCOUNT  PEDCYLCOUNT  VEHCOUNT                 INCDATE  \
0         0            0         2  2013/03/27 00:00:00+00   
1         0            0         2  2006/12/20 00:00:00+00   
2         0            0         3  2004/11/18 00:00:00+00   
3         0            0         3  2013/03/29 00:00:00+00   
4         0            0         2  2004/01/28 00:00:00+00   

                  INCDTTM                             JUNCTIONTYPE  \
0    3/27/2013 2:54:00 PM   At Intersection (intersection related)   
1   12/20/2006 6:55:00 PM  Mid-Block (not related to intersection)   
2  11/18/2004 10:20:00 AM  Mid-Block (not related to intersection)   
3    3/29/2013 9:26:00 AM  Mid-Block (not related to intersection)   
4    1/28/2004 8:04:00 AM   At Intersection (intersection related)   

   SDOT_COLCODE                                       SDOT_COLDESC  \
0            11  MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...   
1            16  MOTOR VEHICLE STRUCK MOTOR VEHICLE, LEFT SIDE ...   
2            14       MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END   
3            11  MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...   
4            11  MOTOR VEHICLE STRUCK MOTOR VEHICLE, FRONT END ...   

  INATTENTIONIND UNDERINFL   WEATHER ROADCOND                LIGHTCOND  \
0            NaN         N  Overcast      Wet                 Daylight   
1            NaN         0   Raining      Wet  Dark - Street Lights On   
2            NaN         0  Overcast      Dry                 Daylight   
3            NaN         N     Clear      Dry                 Daylight   
4            NaN         0   Raining      Wet                 Daylight   

  PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0           NaN         NaN      NaN         10   
1           NaN   6354039.0      NaN         11   
2           NaN   4323031.0      NaN         32   
3           NaN         NaN      NaN         23   
4           NaN   4028032.0      NaN         10   

                                          ST_COLDESC  SEGLANEKEY  \
0                                  Entering at angle           0   
1  From same direction - both going straight - bo...           0   
2                             One parked--one moving           0   
3                   From same direction - all others           0   
4                                  Enterin

In [3]:
df1 = df[['SEVERITYCODE','WEATHER','ROADCOND','LIGHTCOND']]
df1.head()

SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND
0             2  Overcast      Wet                 Daylight
1             1   Raining      Wet  Dark - Street Lights On
2             1  Overcast      Dry                 Daylight
3             1     Clear      Dry                 Daylight
4             2   Raining      Wet                 Daylight

In [4]:
df1.describe(include='all')

SEVERITYCODE WEATHER ROADCOND LIGHTCOND
count   194673.000000  189592   189661    189503
unique            NaN      11        9         9
top               NaN   Clear      Dry  Daylight
freq              NaN  111135   124510    116137
mean         1.298901     NaN      NaN       NaN
std          0.457778     NaN      NaN       NaN
min          1.000000     NaN      NaN       NaN
25%          1.000000     NaN      NaN       NaN
50%          1.000000     NaN      NaN       NaN
75%          2.000000     NaN      NaN       NaN
max          2.000000     NaN      NaN       NaN

In [5]:
df1.replace(r'^\s*$', np.nan, regex=True)
df1.replace("Unknown", np.nan, inplace = True)
df1.replace("Other", np.nan, inplace = True)
df1.describe(include='all')

D:\Users\ShalomCheng\anaconda3\lib\site-packages\pandas\core\frame.py:4172: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,


SEVERITYCODE WEATHER ROADCOND LIGHTCOND
count   194673.000000  173669   174451    175795
unique            NaN       9        7         7
top               NaN   Clear      Dry  Daylight
freq              NaN  111135   124510    116137
mean         1.298901     NaN      NaN       NaN
std          0.457778     NaN      NaN       NaN
min          1.000000     NaN      NaN       NaN
25%          1.000000     NaN      NaN       NaN
50%          1.000000     NaN      NaN       NaN
75%          2.000000     NaN      NaN       NaN
max          2.000000     NaN      NaN       NaN

In [6]:
df2 = df1.dropna()
df2.describe(include='all')

SEVERITYCODE WEATHER ROADCOND LIGHTCOND
count   169957.00000  169957   169957    169957
unique           NaN       9        7         7
top              NaN   Clear      Dry  Daylight
freq             NaN  108825   121490    112618
mean         1.32763     NaN      NaN       NaN
std          0.46935     NaN      NaN       NaN
min          1.00000     NaN      NaN       NaN
25%          1.00000     NaN      NaN       NaN
50%          1.00000     NaN      NaN       NaN
75%          2.00000     NaN      NaN       NaN
max          2.00000     NaN      NaN       NaN

In [7]:
df2.WEATHER.value_counts()

Clear                       108825
Raining                      32648
Overcast                     26923
Snowing                        825
Fog/Smog/Smoke                 553
Sleet/Hail/Freezing Rain       107
Blowing Sand/Dirt               46
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

In [8]:
df2.ROADCOND.value_counts()

Dry               121490
Wet                46324
Ice                 1080
Snow/Slush           833
Standing Water       105
Sand/Mud/Dirt         65
Oil                   60
Name: ROADCOND, dtype: int64

In [9]:
df2.LIGHTCOND.value_counts()

Daylight                    112618
Dark - Street Lights On      46748
Dusk                          5648
Dawn                          2413
Dark - No Street Lights       1408
Dark - Street Lights Off      1114
Dark - Unknown Lighting          8
Name: LIGHTCOND, dtype: int64

In [10]:
df2.SEVERITYCODE.value_counts()

1    114274
2     55683
Name: SEVERITYCODE, dtype: int64

In [11]:
df2['SEVERITYCODE'].value_counts()

1    114274
2     55683
Name: SEVERITYCODE, dtype: int64

In [12]:
df3= df2.sample(frac=1,random_state=0,replace=False)
df3_scode2 = df3.loc[df['SEVERITYCODE']==2]
df3_scode1 = df3.loc[df['SEVERITYCODE']==1].sample(n=55683,random_state=42)
df_balanced = pd.concat([df3_scode1,df3_scode2])
df_balanced = df_balanced.sample(frac=1,random_state=0,replace=False)
df_balanced['SEVERITYCODE'].value_counts()

2    55683
1    55683
Name: SEVERITYCODE, dtype: int64

In [13]:
df_balanced

SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND
28749              2     Clear      Dry                 Daylight
54623              1   Raining      Dry                 Daylight
76580              2     Clear      Dry  Dark - Street Lights On
135183             2   Raining      Wet  Dark - Street Lights On
173738             1  Overcast      Wet                 Daylight
...              ...       ...      ...                      ...
126997             1     Clear      Dry  Dark - Street Lights On
184529             1     Clear      Dry                 Daylight
67981              1   Raining      Wet                 Daylight
134378             1     Clear      Dry  Dark - Street Lights On
146276             2     Clear      Dry                 Daylight

[111366 rows x 4 columns]

In [14]:
X = df_balanced.iloc[:,1:]
X = pd.get_dummies(data=X, columns=['WEATHER','ROADCOND','LIGHTCOND'])

Y = df_balanced[['SEVERITYCODE']]
print(X.info())
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 111366 entries, 28749 to 146276
Data columns (total 23 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   WEATHER_Blowing Sand/Dirt           111366 non-null  uint8
 1   WEATHER_Clear                       111366 non-null  uint8
 2   WEATHER_Fog/Smog/Smoke              111366 non-null  uint8
 3   WEATHER_Overcast                    111366 non-null  uint8
 4   WEATHER_Partly Cloudy               111366 non-null  uint8
 5   WEATHER_Raining                     111366 non-null  uint8
 6   WEATHER_Severe Crosswind            111366 non-null  uint8
 7   WEATHER_Sleet/Hail/Freezing Rain    111366 non-null  uint8
 8   WEATHER_Snowing                     111366 non-null  uint8
 9   ROADCOND_Dry                        111366 non-null  uint8
 10  ROADCOND_Ice                        111366 non-null  uint8
 11  ROADCOND_Oil                        111366 non-n

In [15]:
#Logistic Regression

lr = LogisticRegression(random_state = 0)
lr.fit(X_train,Y_train)
lr_predictions = lr.predict(X_test)

lr_cm = confusion_matrix(Y_test,lr_predictions)
print(lr_cm,'\n')

lr_cr = classification_report(Y_test,lr_predictions)
print(lr_cr,'\n')

acc = accuracy_score(Y_test,lr_predictions)
print(acc,'\n')
accDict = {}
accDict['LR'] = acc

D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[3735 7433]
 [3324 7782]] 

              precision    recall  f1-score   support

           1       0.53      0.33      0.41     11168
           2       0.51      0.70      0.59     11106

    accuracy                           0.52     22274
   macro avg       0.52      0.52      0.50     22274
weighted avg       0.52      0.52      0.50     22274
 

0.5170602496183891 



D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [16]:
#KNN

knn = KNeighborsClassifier()
params = {'n_neighbors':[3,4,5,6,7],
          'p':[1,2]}
knn1 = GridSearchCV(knn, param_grid=params)
knn1.fit(X_train,Y_train.values.ravel())
knn_predictions = knn1.predict(X_test)

print('Best Hyperparameter KNN : ',knn1.best_params_)

knn_cm = confusion_matrix(Y_test,knn_predictions)
print(knn_cm,'\n')

knn_cr = classification_report(Y_test,knn_predictions)
print(knn_cr,'\n')

acc = accuracy_score(Y_test,knn_predictions)
print(acc,'\n')
accDict['KNN'] = acc

Best Hyperparameter KNN :  {'n_neighbors': 7, 'p': 1}
[[4308 6860]
 [4010 7096]] 

              precision    recall  f1-score   support

           1       0.52      0.39      0.44     11168
           2       0.51      0.64      0.57     11106

    accuracy                           0.51     22274
   macro avg       0.51      0.51      0.50     22274
weighted avg       0.51      0.51      0.50     22274
 

0.511987070126605 



In [17]:
#Naive Bayes

nb = GaussianNB()
nb.fit(X_train,Y_train)
nb_predictions = nb.predict(X_test)

nb_cm=confusion_matrix(Y_test,nb_predictions)
print(nb_cm,'\n')

nb_cr = classification_report(Y_test,nb_predictions)
print(nb_cr,'\n')

acc = accuracy_score(Y_test,nb_predictions)
print(acc,'\n')
accDict['NB'] = acc

[[  345 10823]
 [  206 10900]] 

              precision    recall  f1-score   support

           1       0.63      0.03      0.06     11168
           2       0.50      0.98      0.66     11106

    accuracy                           0.50     22274
   macro avg       0.56      0.51      0.36     22274
weighted avg       0.56      0.50      0.36     22274
 

0.5048487025231211 



D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
#Decision Tree Classifier

dtc = DecisionTreeClassifier()
params = {'criterion':['gini', 'entropy'], 
          'random_state':[0]}

dtc1 = GridSearchCV(dtc, param_grid=params)
dtc1.fit(X_train,Y_train)
dtc_predictions = dtc1.predict(X_test)
print('Best Hyperparameter DTC : ',dtc1.best_params_)


dtc_cm=confusion_matrix(Y_test,dtc_predictions)
print(dtc_cm,'\n')

dtc_cr = classification_report(Y_test,dtc_predictions)
print(dtc_cr,'\n')

acc = accuracy_score(Y_test,dtc_predictions)
print(acc,'\n')
accDict['DTC'] = acc

Best Hyperparameter DTC :  {'criterion': 'gini', 'random_state': 0}
[[3644 7524]
 [3263 7843]] 

              precision    recall  f1-score   support

           1       0.53      0.33      0.40     11168
           2       0.51      0.71      0.59     11106

    accuracy                           0.52     22274
   macro avg       0.52      0.52      0.50     22274
weighted avg       0.52      0.52      0.50     22274
 

0.5157133878064111 



In [19]:
#Random Forest Classifer

rf = RandomForestClassifier()
params = {'n_estimators':[50,75,100],
          'criterion':['gini', 'entropy'], 
          'random_state':[0]}
rf1 = GridSearchCV(rf, param_grid=params)
rf1.fit(X_train,Y_train)
rf_predictions = rf1.predict(X_test)
print('Best Hyperparameter RFT : ',rf1.best_params_)

rf_cm=confusion_matrix(Y_test,rf_predictions)
print(rf_cm,'\n')

rf_cr = classification_report(Y_test,rf_predictions)
print(rf_cr,'\n')

acc = accuracy_score(Y_test,rf_predictions)
print(acc,'\n')
accDict['RFT'] = acc

D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarni

D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:739: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


Best Hyperparameter RFT :  {'criterion': 'gini', 'n_estimators': 100, 'random_state': 0}
[[3638 7530]
 [3257 7849]] 

              precision    recall  f1-score   support

           1       0.53      0.33      0.40     11168
           2       0.51      0.71      0.59     11106

    accuracy                           0.52     22274
   macro avg       0.52      0.52      0.50     22274
weighted avg       0.52      0.52      0.50     22274
 

0.5157133878064111 



In [20]:
#SVM

svc = SVC()
params = {'kernel':['linear','rbf'], 
          'random_state':[0]}
svc1 = GridSearchCV(svc, param_grid=params)
svc1.fit(X_train,Y_train)
svc_predictions = svc1.predict(X_test)
print('Best Hyperparameter SVM : ',svc1.best_params_)

svc_cm=confusion_matrix(Y_test,svc_predictions)
print(svc_cm,'\n')

svc_cr = classification_report(Y_test,svc_predictions)
print(svc_cr,'\n')

acc = accuracy_score(Y_test,svc_predictions)
print(acc,'\n')
accDict['SVC'] = acc

D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Users\ShalomCheng\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape

Best Hyperparameter SVM :  {'kernel': 'rbf', 'random_state': 0}
[[3615 7553]
 [3237 7869]] 

              precision    recall  f1-score   support

           1       0.53      0.32      0.40     11168
           2       0.51      0.71      0.59     11106

    accuracy                           0.52     22274
   macro avg       0.52      0.52      0.50     22274
weighted avg       0.52      0.52      0.50     22274
 

0.5155787016252132 



In [21]:
accDict

{'LR': 0.5170602496183891,
 'KNN': 0.511987070126605,
 'NB': 0.5048487025231211,
 'DTC': 0.5157133878064111,
 'RFT': 0.5157133878064111,
 'SVC': 0.5155787016252132}